### PR TITLE
Finished with the backend

### PR DESCRIPTION
**Pull request by RealYusufIsmail**

### CODE REVIEW

**Review by Haleloch — DISMISSED** [review]

**Review by Haleloch — APPROVED** [review]
Ok but some methods are empty
Is it normal ?

**Comment by RealYusufIsmail** [comment]
> Ok but some methods are empty
> 
> Is it normal ?

Yeah.

**Comment by RealYusufIsmail** [comment]
> Ok but some methods are empty
> 
> Is it normal ?

The ones in the abstract classes are meant to be empty as you can extend the class and overuse and use them.

**Comment by RealYusufIsmail** [comment]
They are not abstract as they are optional to use unlike for example the slash command interaction were that is required to run a slash command.

**Pull request merged**
